config/routes.rb
Rails.application.routes.draw do
root "creatures#index"

  get "/creatures", to: "creatures#index", as: "creatures"
  get "/creatures/new", to: "creatures#new", as: "new_creatures"
  post "/creatures", to: "creatures#create"
  get "/creatures/:id", to: "creatures#show", as: "creature"
  get "/creatures/:id/edit", to: "creatures#edit", as: "edit_creature"
  patch "/creatures/:id", to: "creatures#update"
  #put "/creatures/:id", to: "creatures#update", as:  #optional
  delete "/creatures/:id", to: "creatures#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
  @creatures = Creature.all
  end

  # show the new creature form
  def new
    @creature = Creature.new
    # remember the default behavior is to render :new
  end

  def create 
    # white list params
    creature_params = params.require(:creature).permit(:name, :description)

    # create a new creature in the database from the params
    creature = Creature.new(creature_params)

    # if creature saves, redirect to route that displays
    # ONLY the newly created creature
    if creature.save
      redirect_to creatures_path(creature)
      # redirect_to creature_path(creature) is equivalent to:
      # redirect_to creature "/creatures/#{creature.id} "
    end
  end

  def show
    # get the creature id from the url params
    creature_id = params[:id]

    # use `creature_id` to find the creature in the database
    # and save it to an instance variable
    @creature = Creature.find_by_id(creature_id)

    # render the show view (it has access to instance variable)
    # remember the default behavior is to render :show
    
  end

  # show the edit creature form
  def edit
    # get the creature id from the url params
    creature_id = params[:id]

    # use `creature_id` to find creature in the database
    # and save it to the instance variable
    @creature = Creature.find_by_id(creature_id)
    # render the edit view (it has access to instance variable)
  end

  # update creature in the database
  def update
    # get the creature id from the url params
    creature_id = params[:id]

    # use the `creature_id` to find the creature in the database 
    creature = Creature.find_by_id(creature_id)

    # whitelist params and save to variable
    creature_params = params.require(:creature).permit(:name, :description)

    # update the creature based on params
    creature.update_attributes(creature_params)

    # redirect the show page for the updated creature
    redirect_to creature_path(creature)
    # redirect_to creature_path(creature) is equivalent to:
    # redirect_to "/creatures/#{creature.id}"
    
  end
  # delete a creature from a database
  def destroy
    # get the creature id from the url params
    creature_id = params[:id]

    # use `creature_id` to find the creature from the database and save it
    creature = Creature.find_by_id(creature_id)

    # destroy the creature
    creature.destroy

    # redirect to creature index
    redirect_to creatures_path
    # redirect_to creature_path is equivalent to:
    # redirect_to "/creatures"
  end

  private

  def creature_params
    # whitelist params return whitelist version
    params.require(:creature).permit(:name, :description)
  end
end
     

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<%= form_for @creature do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.submit "Save Creature" %>
  <%= link_to "update", edit_creature_path(@creature) %>
<% end %>

app/views/creatures/index.html.erb
<!-- app/views/creatures/index.html.erb -->
  
<ul class="collection">
  <%  @creatures.each do |creature| %>
    <li class="collection-item">
      <strong>Name:</strong> <%= creature.name %> <br>
      <strong>Description:</strong> <%= creature.description %>
      <br>
      <%= link_to "show", creature_path(creature) %>
      <br>
      <%= link_to "update", edit_creature_path(creature) %>
    </li>
  <% end %>
    <%=link_to "new", new_creatures_path(@creatures)%>
</ul>
     
          

app/views/creatures/new.html.erb
<%= form_for :creature, url: "/creatures", method: "post" do |f| %>
 Name: <%=  f.text_area :name %>
 Description: <%= f.text_area :description %>
 <%= link_to "index", creatures_path(@creature) %>
  <%= f.submit "Save Creature" %>
<% end %>
  

app/views/creatures/show.html.erb
<h3><%= @creature.name %></h3>


<%= form_for @creature do |f| %>
  <%= f.text_field :name %><br />

  
  <%= f.text_field :description %><br />
  <%= button_to "Delete", @creature, method: :delete %>
  
<% end %>
  <%= link_to "index", creatures_path(@creature) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BogAppThree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col m6 offset-m3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>